### ISSUE TITLE
Hiring next steps

### ISSUE THREAD

**Issue by jessicaguo** [az-digitalag/organization#826] opened 2022-02-23 17:53 UTC
First round screening interviews completed. 
- [x] Send followup email re: interview with Maliaca to all (?) candidates
- [ ] Invite top candidates to schedule in-person, full day interviews
- [ ] Coordinate admin with business office + Maliaca

**Comment by dlebauer** [comment] 2022-02-28 19:57
Closing as duplicate of #806

**Closed by dlebauer** 2022-02-28 19:57 UTC
