### ISSUE TITLE
Test (and report error) if methods association in BETY bulk upload actually doesn't work

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#12] opened 2019-04-18 22:24 UTC

**Comment by dlebauer** [comment] 2019-05-31 17:45
please provide the reproducible example (csv file)

**Comment by kimberlyh66** [comment] 2019-08-05 18:28
The following files containing `leaf_length` and `leaf_width` data were upload by Zeyu Zhang. However, method association in BETY bulk upload did not work and data were not associated with selected method `3D scanner to leaf length and width`.

[width.xlsx](https://github.com/az-digitalag/organization/files/3468870/width.xlsx)
[length.xlsx](https://github.com/az-digitalag/organization/files/3468868/length.xlsx)

**Comment by dlebauer** [comment] 2019-08-05 18:40
have updated the methods

```sql
begin;
update traits
  set method_id = (select id from methods where name = '3D scanner to leaf length and width')
    where citation_id = (select id from citations where author = 'Zeyu Zhang')
    and variable_id in (select id from variables where name in ('leaf_length', 'leaf_width'));
commit;
```

**Comment by dlebauer** [comment] 2019-08-05 18:46
@kimberlyh66 can you confirm that you attempted to assign the method in the 'global values' page rather than in the csv file?

It is still an odd bug, but at least the limitation is buried somewhere in our [(updated) documentation](https://pecanproject.github.io/bety-documentation/dataentry/adding-trait-and-yield-data.html#using-the-bulk-upload-wizard) just above the 'using the bulk upload wizard' section:


![image](https://user-images.githubusercontent.com/464871/62487336-66c94080-b776-11e9-9ec6-0fa8ed3da7fd.png)

**Comment by kimberlyh66** [comment] 2019-08-05 19:09
Since Zeyu uploaded the data, I will need to double check with him if he assigned the method using the 'global values' page. Looking back at our slack messages, it looks like he mentioned selecting a method in the dataset-wide values page - is this the same as the global values page?

**Comment by kimberlyh66** [comment] 2019-08-05 19:24
Zeyu has confirmed that he selected the method interactively during the bulk upload.

**Comment by dlebauer** [comment] 2019-08-05 23:07
Will be fixed by https://github.com/PecanProject/bety/pull/658

**Closed by dlebauer** 2019-08-05 23:07 UTC
