### ISSUE TITLE
Fix Welsch-to-HPC rsync error

### ISSUE THREAD

**Issue by KristinaRiemer** [az-digitalag/organization#411] opened 2021-03-11 19:04 UTC
When doing rsync from Welsch directories to UA HPC directories, such as `rsync '-az' '-q' 'kristinariemer@login.ocelote.hpc.arizona.edu:/home/u29/kristinariemer/pecan_remote/2021-02-27-00-40-04/out' '/data/tests/ed2'`, sometimes the rsync doesn't occur at all or only some of the files are transferred successfully. That command, for example, result in the below error the first time I ran it but then worked fine the second time immediately afterwards. 

```
client_loop: send disconnect: Broken pipe
rsync: connection unexpectedly closed (1476205 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [receiver=3.0.6]
rsync: connection unexpectedly closed (4549 bytes received so far) [generator]
rsync error: unexplained error (code 255) at io.c(600) [generator=3.0.6]
```

See [Slack thread](https://cyverse.slack.com/archives/CQAATRMCM/p1614178933005200) for a few more details.

**Comment by KristinaRiemer** [comment] 2021-03-12 15:23
Got this again today: 

```
kristinariemer@0b8767da37cc:~/model-vignettes$ rsync '-az' '-q' 'kristinariemer@login.ocelote.hpc.arizona.edu:/groups/dlebauer/ed2_results/pecan_remote/2021-03-11-18-52-54/out' '/data/tests/ed2'
client_loop: send disconnect: Broken pipe
rsync: connection unexpectedly closed (187042427 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(600) [receiver=3.0.6]
rsync: connection unexpectedly closed (6286 bytes received so far) [generator]
rsync error: unexplained error (code 255) at io.c(600) [generator=3.0.6]
```

**Comment by julianpistorius** [comment] 2021-03-18 22:31
@KristinaRiemer could you please try a couple of things for me:

1. Use `sftp.hpc.arizona.edu` instead of `login.ocelote.hpc.arizona.edu`: 
    ```bash
    rsync '-az' '-q' 'kristinariemer@sftp.hpc.arizona.edu/groups/dlebauer/ed2_results/pecan_remote/2021-03-11-18-52-54/out' '/data/tests/ed2'
    ```
2. Use `scp` instead of `rsync`:
    ```bash
     scp '-r' '-q' 'kristinariemer@sftp.hpc.arizona.edu/groups/dlebauer/ed2_results/pecan_remote/2021-03-11-18-52-54/out' '/data/tests/ed2'
    ```

**Comment by julianpistorius** [comment] 2021-03-29 16:49
Kristina could not reproduce this. Not sure whether to create a follow-up ticket, close this, or move it to follow-up.

**Comment by KristinaRiemer** [comment] 2021-03-29 20:18
I haven't had this happen to me in the past couple of weeks either. I'm not sure why, maybe we could close this until it happens again (if it does)?

**Closed** 2021-04-28 19:06 UTC
